# Stage 1: Builder
FROM python:3.10-slim as builder

WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --prefix=/install -r requirements.txt

COPY . .

# Stage 2: Runtime
FROM python:3.10-alpine

COPY --from=builder /install /usr/local
COPY --from=builder /app /app

WORKDIR /app
CMD ["python", "main.py"]
